name: Flutter APK Build

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'temurin' or 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # Specify Flutter version 3.24.3

      - name: Install dependencies
        run: flutter pub get
      
      - name: Generate firebase_options.dart
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        run: |
          mkdir -p lib
          echo "import 'package:firebase_core/firebase_core.dart';" > lib/firebase_options.dart
          echo "const FirebaseOptions firebaseOptions = FirebaseOptions(" >> lib/firebase_options.dart
          echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> lib/firebase_options.dart
          echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'," >> lib/firebase_options.dart
          echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> lib/firebase_options.dart
          echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> lib/firebase_options.dart
          echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> lib/firebase_options.dart
          echo ");" >> lib/firebase_options.dart

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
